[snowpark]
account= 'au42629.eu-central-1'
user= 'finaxysaccount1'
password= 'Finaxys@2023'
role= 'DATADAY'
warehouse= 'DATADAY_WH'
database= 'TRADER_ACCOUNT_DD2'
schema= 'PUBLIC'
client_session_keep_alive= 'True'